[project]
name = "fast-api-project-rag"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "email-validator>=2.3.0",
    "fastapi[standard]>=0.141.1",
    "bcrypt==4.0.1",
    "passlib[bcrypt]>=1.7.4",
    "psycopg2>=2.9.12",
    "psycopg[binary]>=3.3.5",
    "python-dotenv>=1.2.3",
    "python-jose>=3.5.0",
    "sqlalchemy>=2.0.52",
]
